# Generated by Django 5.2.1 on 2025-05-30 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GearSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("start", "출발"),
                            ("final", "최종"),
                            ("current", "현재"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("weapon", "무기"),
                            ("head", "머리"),
                            ("body", "상의"),
                            ("hands", "장갑"),
                            ("legs", "하의"),
                            ("feet", "신발"),
                            ("earring", "귀걸이"),
                            ("necklace", "목걸이"),
                            ("bracelet", "팔찌"),
                            ("ring", "반지"),
                            ("reinforce", "보강재"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("heroic", "영웅 레이드"),
                            ("normal", "일반 레이드"),
                            ("tome", "석판"),
                            ("crafted", "제작"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_reinforced", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("icon_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tank", "탱커"),
                            ("healer", "힐러"),
                            ("melee", "근딜"),
                            ("ranged", "원딜"),
                            ("caster", "마딜"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "color",
                    models.CharField(blank=True, default="#FFFFFF", max_length=7),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("weapon", "무기"),
                            ("head", "머리"),
                            ("body", "상의"),
                            ("hands", "장갑"),
                            ("legs", "하의"),
                            ("feet", "신발"),
                            ("earring", "귀걸이"),
                            ("necklace", "목걸이"),
                            ("bracelet", "팔찌"),
                            ("ring", "반지"),
                            ("reinforce", "보강재"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gearset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="raid.gearset",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="raid.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="raid.job"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LootHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acquired_at", models.DateField()),
                ("source", models.CharField(max_length=30)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="raid.item"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="raid.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gearset",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gearsets",
                to="raid.player",
            ),
        ),
        migrations.CreateModel(
            name="RaidGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("raid_name", models.CharField(max_length=100)),
                ("item_level", models.IntegerField()),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaidEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="raid.raidgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="raid.raidgroup",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="raid.role",
            ),
        ),
    ]
